version: '3.7'
services:
  db:
    image: academystep/example-image:1.0.0
    ports:
    - 8081:8080
    environment:
      - DATABSE_URL=localhost:3306
      - DATABSE_USER=root
      - DATABSE_PASSWORD=root
      - PORT=8080
    depends_on:
      - 'db'
    restart: on-failure



